# Generated by Django 4.2.7 on 2025-04-14 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_response_academic_year_response_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='course',
        ),
        migrations.DeleteModel(
            name='LecturerUnit',
        ),
    ]
